# This did its job admirably, and I'm so proud of how concise
# and elegant this is!

# This will need to scrub the data of unnecessary (but helpful!)
# data at the top and bottom of the rainfall stuff, and turn it
# into something Pandas-able. Rainfall data can be found here:
# https://www.vcwatershed.net/hydrodata/php/getstations.php?dataset=rain_day&order=name

# The location of the rainfall data is data/rainfall/for <station name>

import re

listofrainfallstations = {'for ME-CC': ['sta505_2010_daily.csv',
                                        'sta505_2011_daily.csv',
                                        'sta505_2012_daily.csv',
                                        'sta505_2013_daily.csv',
                                        'sta505_2014_daily.csv',
                                        'sta505_2015_daily.csv',
                                        'sta505_2016_daily.csv',
                                        'sta505_2017_daily.csv',
                                        'sta505_2018_daily.csv',
                                        'sta505_2019_daily.csv',
                                        'sta505_2020_daily.csv'],
                          'for ME-VR2': ['sta122_2010_daily.csv',
                                         'sta122_2011_daily.csv',
                                         'sta122_2012_daily.csv',
                                         'sta122_2013_daily.csv',
                                         'sta122_2014_daily.csv',
                                         'sta122_2015_daily.csv',
                                         'sta122_2016_daily.csv',
                                         'sta122_2017_daily.csv',
                                         'sta122_2018_daily.csv',
                                         'sta122_2019_daily.csv',
                                         'sta122_2020_daily.csv'],
                          'for MO-CAM': ['sta259_2010_daily.csv',
                                         'sta259_2011_daily.csv',
                                         'sta259_2012_daily.csv',
                                         'sta259_2013_daily.csv',
                                         'sta259_2014_daily.csv',
                                         'sta259_2015_daily.csv',
                                         'sta259_2016_daily.csv',
                                         'sta259_2017_daily.csv',
                                         'sta259_2018_daily.csv',
                                         'sta259_2019_daily.csv',
                                         'sta259_2020_daily.csv'],
                          'for MO-FIL': ['sta199A_2010_daily.csv',
                                         'sta199A_2011_daily.csv',
                                         'sta199A_2012_daily.csv',
                                         'sta199A_2013_daily.csv',
                                         'sta199A_2014_daily.csv',
                                         'sta199A_2015_daily.csv',
                                         'sta199A_2016_daily.csv',
                                         'sta199A_2017_daily.csv',
                                         'sta199A_2018_daily.csv',
                                         'sta199A_2019_daily.csv',
                                         'sta199A_2020_daily.csv'],
                          'for MO-HUE': ['sta017C_2010_daily.csv',
                                         'sta017C_2011_daily.csv',
                                         'sta017C_2012_daily.csv',
                                         'sta017C_2013_daily.csv',
                                         'sta017C_2014_daily.csv',
                                         'sta017C_2015_daily.csv',
                                         'sta017C_2016_daily.csv',
                                         'sta017C_2017_daily.csv',
                                         'sta017C_2018_daily.csv',
                                         'sta017C_2019_daily.csv',
                                         'sta017C_2020_daily.csv'],
                          'for MO-MEI': ['sta218_2010_daily.csv',
                                         'sta218_2011_daily.csv',
                                         'sta218_2012_daily.csv',
                                         'sta218_2013_daily.csv',
                                         'sta218_2014_daily.csv',
                                         'sta218_2015_daily.csv',
                                         'sta218_2016_daily.csv',
                                         'sta218_2017_daily.csv',
                                         'sta218_2018_daily.csv',
                                         'sta218_2019_daily.csv',
                                         'sta218_2020_daily.csv'],
                          'for MO-MPK': ['sta508_2010_daily.csv',
                                         'sta508_2011_daily.csv',
                                         'sta508_2012_daily.csv',
                                         'sta508_2013_daily.csv',
                                         'sta508_2014_daily.csv',
                                         'sta508_2015_daily.csv',
                                         'sta508_2016_daily.csv',
                                         'sta508_2017_daily.csv',
                                         'sta508_2018_daily.csv',
                                         'sta508_2019_daily.csv',
                                         'sta508_2020_daily.csv'],
                          'for MO-OJA': ['sta030D_2010_daily.csv',
                                         'sta030D_2011_daily.csv',
                                         'sta030D_2012_daily.csv',
                                         'sta030D_2013_daily.csv',
                                         'sta030D_2014_daily.csv',
                                         'sta030D_2015_daily.csv',
                                         'sta030D_2016_daily.csv',
                                         'sta030D_2017_daily.csv',
                                         'sta030D_2018_daily.csv',
                                         'sta030D_2019_daily.csv',
                                         'sta030D_2020_daily.csv'],
                          'for MO-OXN': ['sta239_2010_daily.csv',
                                         'sta239_2011_daily.csv',
                                         'sta239_2012_daily.csv',
                                         'sta239_2013_daily.csv',
                                         'sta239_2014_daily.csv',
                                         'sta239_2015_daily.csv',
                                         'sta239_2016_daily.csv',
                                         'sta239_2017_daily.csv',
                                         'sta239_2018_daily.csv',
                                         'sta239_2019_daily.csv',
                                         'sta239_2020_daily.csv'],
                          'for MO-SIM': ['sta506_2010_daily.csv',
                                         'sta506_2011_daily.csv',
                                         'sta506_2012_daily.csv',
                                         'sta506_2013_daily.csv',
                                         'sta506_2014_daily.csv',
                                         'sta506_2015_daily.csv',
                                         'sta506_2016_daily.csv',
                                         'sta506_2017_daily.csv',
                                         'sta506_2018_daily.csv',
                                         'sta506_2019_daily.csv',
                                         'sta506_2020_daily.csv'],
                          'for MO-SPA': ['sta245A_2010_daily.csv',
                                         'sta245B_2011_daily.csv',
                                         'sta245B_2012_daily.csv',
                                         'sta245B_2013_daily.csv',
                                         'sta245B_2014_daily.csv',
                                         'sta245B_2015_daily.csv',
                                         'sta245B_2016_daily.csv',
                                         'sta245B_2017_daily.csv',
                                         'sta245B_2018_daily.csv',
                                         'sta245B_2019_daily.csv',
                                         'sta245B_2020_daily.csv'],
                          'for MO-THO': ['sta188A_2010_daily.csv',
                                         'sta188A_2011_daily.csv',
                                         'sta188A_2012_daily.csv',
                                         'sta188A_2013_daily.csv',
                                         'sta188A_2014_daily.csv',
                                         'sta188A_2015_daily.csv',
                                         'sta188A_2016_daily.csv',
                                         'sta188A_2017_daily.csv',
                                         'sta188A_2018_daily.csv',
                                         'sta188A_2019_daily.csv',
                                         'sta188A_2020_daily.csv'],
                          'for MO-VEN': ['sta175A_2010_daily.csv',
                                         'sta175A_2011_daily.csv',
                                         'sta175A_2012_daily.csv',
                                         'sta175A_2013_daily.csv',
                                         'sta175A_2014_daily.csv',
                                         'sta175A_2015_daily.csv',
                                         'sta175A_2016_daily.csv',
                                         'sta175A_2017_daily.csv',
                                         'sta175A_2018_daily.csv',
                                         'sta175A_2019_daily.csv',
                                         'sta175A_2020_daily.csv']}

for stationname in listofrainfallstations.keys():
    with open(f'data/rainfall/{stationname.replace("for ", "")}rainfall.csv', 'w') as file:
        file.write("24 Hour Total Ending At,Rainfall (in),Code,Quality Code,Publish")

for monitoringstation in listofrainfallstations.keys():  # e.g., "for ME-CC"
    # open the file in data/rainfall called e.g., "ME-CCrainfall.csv"
    rainfalldatafile = open(file=f'data/rainfall/{monitoringstation.replace("for ", "")}rainfall.csv', mode='a')
    for rainfalldata in listofrainfallstations[monitoringstation]:  # i.e. "sta505_2010_daily.csv"
        datalines = open(file=f'data/rainfall/{monitoringstation}/{rainfalldata}').read().split(sep='\n')
        for line in datalines:
            words = line.split(sep=' ')
            if re.search(pattern=r'\d{1,2}/\d{1,2}/\d{4}', string=words[0]) is not None:
                print(f'{line}\t\t{monitoringstation}\t\t{rainfalldata}')
                rainfalldatafile.write(f'\n{line}')
